// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzmnbEiB4vfsSvXg0G9l-5lEFQ4P7zvo',
    appId: '1:311375627670:web:94cbfa87b75af3d8e5c9b7',
    messagingSenderId: '311375627670',
    projectId: 'todo-76f6d',
    authDomain: 'todo-76f6d.firebaseapp.com',
    storageBucket: 'todo-76f6d.appspot.com',
    measurementId: 'G-JSYM836QLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaVMSQRGHXAWPjRStXlUwThMoQjMiP0C4',
    appId: '1:311375627670:android:abc8ea1385f38bbae5c9b7',
    messagingSenderId: '311375627670',
    projectId: 'todo-76f6d',
    storageBucket: 'todo-76f6d.appspot.com',
  );
}
